#Valid locators for login page
login.username=//input[@placeholder='username']
login.password=//input[@placeholder='password']
login.button=//button[@type='submit']
login.dashboard=//div[@class='oxd-topbar-header-title']
#login.error=.oxd-alert-content-text